import React, {useEffect} from 'react'
import Navbar from './components/Navbar'
import Hero from './components/Hero'
import About from './components/About'
import Experience from './components/Experience'
import Projects from './components/Projects'
import Education from './components/Education'
import Skills from './components/Skills'
import Contact from './components/Contact'
import Footer from './components/Footer'
export default function App(){ useEffect(()=>{ const st=document.createElement('button'); st.id='scrollTop'; st.innerText='↑'; document.body.appendChild(st); const onScroll=()=>{ const s=document.getElementById('scrollTop'); if(window.scrollY>400) s.style.display='block'; else s.style.display='none' }; window.addEventListener('scroll', onScroll); st.onclick=()=>window.scrollTo({top:0,behavior:'smooth'}); return ()=>{ window.removeEventListener('scroll', onScroll); st.remove() } },[]); return (<div><Navbar/><main className='pt-24'><Hero/><About/><Experience/><Projects/><Education/><Skills/><Contact/></main><Footer/></div>) }
